# Generated by Django 3.2.21 on 2023-09-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='trainer',
            name='mobilenumber',
            field=models.CharField(default='1234', max_length=20),
        ),
    ]
