# Generated by Django 3.2.21 on 2023-09-18 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_trainer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='BATCH',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.batch'),
        ),
        migrations.CreateModel(
            name='workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('video', models.CharField(max_length=500)),
                ('TRAINER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('TRAINER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=3)),
                ('weight', models.CharField(max_length=3)),
                ('activelevel', models.CharField(max_length=20)),
                ('medical', models.CharField(max_length=20)),
                ('bmi', models.CharField(max_length=3)),
                ('foodtype', models.CharField(max_length=10)),
                ('target', models.CharField(max_length=10)),
                ('allergies', models.CharField(max_length=500)),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('file', models.CharField(max_length=500)),
                ('TRAINER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.trainer')),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('usertype', models.CharField(max_length=10)),
                ('chat', models.CharField(max_length=100)),
                ('TRAINER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.trainer')),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
