# Generated by Django 3.2.21 on 2023-09-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_tips_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
