# Generated by Django 3.2.21 on 2023-09-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_workout_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
