# Generated by Django 3.2.21 on 2023-11-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20231101_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='health',
            name='targetweight',
            field=models.CharField(default='', max_length=10),
        ),
    ]
