# Generated by Django 3.2.21 on 2023-11-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_health_medical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='bmi',
            field=models.CharField(max_length=10),
        ),
    ]
