# Generated by Django 3.2.21 on 2023-11-06 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20231106_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
    ]
