# Generated by Django 3.2.21 on 2024-02-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_workout_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='description',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='tips',
            name='description',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='workout',
            name='video',
            field=models.CharField(max_length=10000),
        ),
    ]
