# Generated by Django 3.2.21 on 2024-04-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='health',
            name='progress',
            field=models.CharField(default=0, max_length=500),
        ),
    ]
